kind: wasmer.io/App.v0

name: AlignAssist

owner: aqibshabbirdev

# Static site — no package
static:
  dir: .

# Optional: routing rules
routes:
  - path: /
    serve: index.html

# Optional headers (recommended)
headers:
  - path: "**"
    headers:
      Cache-Control: public, max-age=3600
